### ISSUE TITLE
"streamlit" not found in Docker image

### ISSUE THREAD

**Issue by msabramo** [samdobson/helm#3]
I worked around #2 (by pasting my Python code right into the `data.streamlit_app.py` key in `templates/configmap.yaml` - hack of course) and noticed another problem:

```
$ helm install my-streamlit-app .
NAME: my-streamlit-app
LAST DEPLOYED: Tue Apr 12 12:50:19 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=streamlit,app.kubernetes.io/instance=my-streamlit-app" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT

$ kubectl describe pod $POD_NAME | egrep --after=11 'Containers:'
Containers:
  streamlit:
    Container ID:   docker://188c5a865465b0b4512ac8762a3af8e61a2311bde920efcbc122395b9fff28f7
    Image:          samdobson/streamlit:1.2.0
    Image ID:       docker-pullable://samdobson/streamlit@sha256:f9c0f60e35550d95ef5d4a3924830e89520882d50d8f79f0ae328f38d3087faf
    Port:           8501/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:380: 
                    starting container process caused: exec: 
                    "streamlit": executable file not found in $PATH: unknown
```

so it seems that the `samdobson/streamlit:1.2.0` Docker image (which is the default image I guess) doesn't have `streamlit` in it.

I confirmed this with:

```
$ docker run -it --rm samdobson/streamlit:1.2.0
docker: Error response from daemon: failed to create shim:
OCI runtime create failed: container_linux.go:380: 
starting container process caused: exec: 
"streamlit": executable file not found in $PATH: unknown.
```

though the `latest` image seems to have it:

```
$ docker run -it --rm samdobson/streamlit:latest

  You can now view your Streamlit app in your browser.

  Network URL: http://172.17.0.2:8501
  External URL: http://73.189.248.220:8501
```

1.1.0 is also missing `streamlit`:

```
$ docker run -it --rm samdobson/streamlit:1.1.0
docker: Error response from daemon: failed to create shim: 
OCI runtime create failed: container_linux.go:380: 
starting container process caused: exec: 
"streamlit": executable file not found in $PATH: unknown.
```

Ditto for 0.89.0 and 0.84.2.

It looks like 0.84.1 has `streamlit` although it shows a different error:

```
$ docker run -it --rm samdobson/streamlit:0.84.1
2022-04-12 20:25:34.931 Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/script_runner.py", line 349, in _run_script
    exec(code, module.__dict__)
  File "/usr/src/app/streamlit_app.py", line 56, in <module>
    display, editor = st.columns((2, 1))
AttributeError: module 'streamlit' has no attribute 'columns'


  You can now view your Streamlit app in your browser.

  Network URL: http://172.17.0.2:8501
  External URL: http://73.189.248.220:8501
```

so I guess something happened between 0.84.1 and 0.84.2?

The newest image I could find that doesn't show any errors is 0.83.0:

```
$ docker run -it --rm samdobson/streamlit:0.83.0

  You can now view your Streamlit app in your browser.

  Network URL: http://172.17.0.2:8501
  External URL: http://73.189.248.220:8501
```

**Comment by samdobson** [comment]
Thanks for reporting. You're right - some of the images in the docker hub repository referenced by this helm chart were broken. There were various incompatibilities between streamlit, its dependencies and Python. Making sure all of these parts are in sync is definitely not trivial.

Looks like we're good now though: all of the [docker hub images](https://hub.docker.com/repository/docker/samdobson/streamlit/tags?page=1&ordering=name) are working, right the way back to the first release of 2021 (`0.74.0`). Streamlit versions before `0.79.0` will show a warning, because [streamlit-ace](https://github.com/okld/streamlit-ace) compatibility breaks at this point, but I'm calling that a "won't fix" given its a dependency of the bundled sample app, which is supposed to be replaced by the user anyway.

In light of the above, I'm going to call this one "done" and close the issue, but feel free to open a new one if you spot anything else.

**Comment by msabramo** [comment]
Thanks, @samdobson!
